---
- name: Create data path
  file:
    path: "{{ generic_postgresql_base_path }}"
    state: directory
    recurse: true
    owner: "{{ generic_postgresql_uid }}"
    group: "{{ generic_postgresql_gid }}"

- name: Create additional paths
  file:
    path: "{{ item }}"
    state: directory
    recurse: true
    owner: "{{ generic_postgresql_uid }}"
    group: "{{ generic_postgresql_gid }}"
  loop: "{{ generic_postgresql_additional_path }}"

- name: Deploy container
  docker_container:
    name: "{{ generic_postgresql_container_name }}"
    image: "{{ generic_postgresql_container_image }}"
    user: "{{ generic_postgresql_uid }}:{{ generic_postgresql_gid }}"
    published_ports: "{{ generic_postgresql_container_ports }}"
    env: "{{ generic_postgresql_container_env | combine(generic_postgresql_container_additional_env) }}"
    volumes: "{{ generic_postgresql_container_volumes }}"
    links: "{{ generic_postgresql_container_links }}"
    state: "{{ generic_postgresql_container_state }}"
    recreate: "{{ generic_postgresql_container_recreate }}"
    auto_remove: "{{ generic_postgresql_container_auto_remove }}"
    cpu_quota: "{{ generic_postgresql_container_cpu_quota }}"
    memory_reservation: "{{ generic_postgresql_container_memory_reservation }}"
    memory_swap: "{{ generic_postgresql_container_memory_swap }}"
    network_mode: "{{ generic_postgresql_container_network_mode }}"
    networks: "{{ generic_postgresql_container_networks }}"
    restart: "{{ generic_postgresql_container_restart }}"
    restart_policy: "{{ generic_postgresql_container_restart_policy }}"